### ISSUE TITLE
통계 자료를 precompute하여 DB에 저장하기

### ISSUE THREAD

**Issue by pingpingy1** [NewWays-TechForImpactKAIST/backend-python#8]
프론트에서 보여주고자 하는 [템플릿](https://www.notion.so/tech4impact/047eb28811f544eaad4db936a727d693?pvs=4)에는 다양성 지수에 따른 순위가 많이 등장합니다.
GET request가 올 때마다 다양성 지수를 계산하는 현재의 방식으로는 매번 모든 의회의 다양성 지수를 다시 계산해야 하기 때문에, 현재 DB에 존재하는 `age_hist`와 `age_stat`과 같이 다양성 지수와 순위를 DB에 저장하면 어떨까 합니다.

<img width="341" alt="image" src="https://github.com/NewWays-TechForImpactKAIST/backend-python/assets/94441510/e0251298-a211-4b33-a86b-8ce1e1136217">

위 그림과 같이 `stats`라는 database 하에 `age_hist`, `age_stat` 등을 collection으로 강등하고, 현재 `f"지선-당선_{year}_1level_{method}"`와 같이 이름으로 구분하던 collection들을 document로 강등하는 것을 제안합니다.
즉, 2010년 지선 서울시 당선인들의 equal 연령 히스토그램 정보를 얻고 싶으면 다음과 같이 쿼리할 수 있습니다.
`MongoDB.client.stats_db["age_hist"].find({"year": 2010, "councilorType": "elected", "metroId": 1, "method": "equal"}).to_list()`
해당 호출의 결과로 얻는 리스트의 각 원소가 히스토그램의 각 bin으로 해석할 수 있도록 설계하면 어떨까 합니다.

DB 구조 변경 계획이 승인되고 구조가 확정된다면 수행해야 작업은 3가지 정도일 것 같습니다.
1. DB에 이미 존재하는 정보를 위와 같은 구조로 수정하기.
2. 다양성 지수 계산, 연령 클러스터링 수행 후 결과를 저장하는 함수 작성/수정하기.
3. 새로운 DB 스키마를 바탕으로 정보를 제공하는 endpoint 수정

내일 시연을 위해서는 우선 쓰레기값이라도 type에 맞게 반환하는 것이 중요하므로, 3번 작업을 가장 선순위로 진행할 계획입니다.

**Comment by Re-st** [comment]
재밌고 좋겠네요. diversity_index, age_hist등을 collection으로 뒀는데, 원래 db였을 때보다 속도나 성능이 떨어질 수 있나요? collection으로 기존정보를 강등하도록 코드를 고치는건 어렵지 않나요, 아니면 오래 걸리나요? 어렵지 않다면, 그냥 지금은 다양성 지수와 순위를 다른 db에 저장하고 나중에 고치는 게 어떤가요?

**Comment by pingpingy1** [comment]
> 재밌고 좋겠네요. diversity_index, age_hist등을 collection으로 뒀는데, 원래 db였을 때보다 속도나 성능이 떨어질 수 있나요? collection으로 기존정보를 강등하도록 코드를 고치는건 어렵지 않나요, 아니면 오래 걸리나요? 어렵지 않다면, 그냥 지금은 다양성 지수와 순위를 다른 db에 저장하고 나중에 고치는 게 어떤가요?

성능은 실제 구현해봐야 알겠지만, 쿼리만 두고 봤을 때는 성능이 저하되더라도 연산 시간을 단축한다는 점에서 이득이지 않을까 희망은 있습니다.
쿼리 로직은 스키마에 아주 민감하기 때문에 일단 저장한 DB에서 쿼리하기 위한 로직은 아마 재사용이 불가하겠지만, 시연이 급한 지금으로선 다른 DB에 저장하는 편도 나쁘진 않을 것 같습니다! 가장 시간이 오래 걸리는 건 반환하는 JSON 타입 정의기도 하고요.
새로 만들 다양성 지수 정보는 상기한 stats/diversity_index에 정의하면 최대한 재사용하기 용이해질 것 같습니다.

그런데 다양성 지수 계산은 백엔드보다는 데이터 리포에서 수행하는 게 더 나을 수도 있겠다는 생각이 드는데, 어떻게 생각하시나요?

**Comment by Re-st** [comment]
그게 맞겠네요. 저는 일단 저장하고 싶은 테이블이 있으면 매번 DB 만드는 식으로 하고 있겠습니다. 나중에 한번에 고칠 수 있으면 고쳐요

**Comment by Re-st** [comment]
그럼 앞으로 저는 코드 지금 그려놓으신 그림 바탕으로 하도록 짜볼게요. 예를 들어, councilors정보가 아직 mongoDB에 안올라가 있으니 저 그림대로 저장됐다 가정하고 해보는 식으로요.

**Comment by pingpingy1** [comment]
> 그게 맞겠네요. 음.. 근데 collection을 document로 바꿀 필요성을 느끼신 걸 보면 현재 구조가 좀 많이 복잡하긴 한가요..

아 구조가 복잡하다는 의미는 아니었고요, 같은 지위에 있는 개체들을 똑같이 document 지위로 저장하는 편이 앞으로 유지보수에 더 용이할 것 같다는 생각이 들었습니다 ㅎㅎ
